"""
Genuine Aadhaar Secure QR verification.

Reads an Aadhaar card (either an uploaded image of the physical card, or a
live webcam frame) and decodes the embedded QR code using pyaadhaar/pyzbar,
then cryptographically verifies the offline XML document embedded in the QR.

The offline Aadhaar QR is a base64-encoded, RSA-SHA256-signed XML document
generated by UIDAI. We:
  1. Decode the QR payload from the image (pyzbar).
  2. Check it is a modern "secure" QR format (pyaadhaar isSecureQr).
  3. Decode + cryptographically verify the embedded signed XML (app.aadhaar),
     which proves the document has not been tampered with since UIDAI issued it.
  4. Return the verified identity fields (name, dob, gender, address, photo).

Imports of pyaadhaar/pyzbar/numpy are lazy so the app always boots even if the
system zbar library is not yet present; QR endpoints surface a clear error in
that case.
"""

from __future__ import annotations

import base64
import io

from .. import aadhaar
from ..errors import AppError

_pyzbar = None
_pyaadhaar = None


def _load_libs():
    """Import optional QR decoding libs once. Returns True if usable.

    On macOS, pyzbar locates libzbar via ``ctypes.util.find_library``, which can
    miss the Homebrew install when DYLD_LIBRARY_PATH is not set. If the standard
    import fails, we explicitly load libzbar from the common Homebrew/usr paths
    and patch pyzbar's loader so subsequent calls reuse the loaded handle.
    """
    global _pyzbar, _pyaadhaar
    if _pyzbar is None:
        try:
            from pyzbar import pyzbar as _pyzbar
        except Exception:
            _ensure_zbar_loaded()
            try:
                from pyzbar import pyzbar as _pyzbar
            except Exception:
                _pyzbar = False
        if _pyzbar:
            try:
                from pyaadhaar.decode import AadhaarSecureQr
                from pyaadhaar.utils import isSecureQr
                _pyaadhaar = {"AadhaarSecureQr": AadhaarSecureQr, "isSecureQr": isSecureQr}
            except Exception:
                _pyaadhaar = None
    return bool(_pyzbar and _pyaadhaar)


def _ensure_zbar_loaded():
    """Load libzbar from known install paths so pyzbar can find it, then
    monkey-patch pyzbar's zbar loader to reuse the loaded handle."""
    import ctypes
    from ctypes import cdll
    from ctypes.util import find_library

    if find_library("zbar"):
        return
    candidates = [
        "/opt/homebrew/lib/libzbar.dylib",
        "/opt/homebrew/lib/libzbar.0.dylib",
        "/usr/local/lib/libzbar.dylib",
        "/usr/lib/libzbar.dylib",
    ]
    loaded = None
    for path in candidates:
        try:
            loaded = cdll.LoadLibrary(path)
            break
        except Exception:
            continue
    if loaded is None:
        return
    try:
        import pyzbar.zbar_library as _zl

        def _patched_load():
            return loaded, []

        _zl.load = _patched_load
    except Exception:
        pass


def with_qr(message: str = "Aadhaar QR decoding is unavailable (zbar not installed)"):
    """Guard decorator/context helper for optional QR libs."""
    return _load_libs() or (_raise(message))


def _raise(message):
    raise AppError(message, 503)


def decode_qr_from_image(image_bytes: bytes) -> list[str]:
    """Find and decode QR payload strings from an Aadhaar card image.

    Accepts a photo of the *whole card* — the QR is located anywhere in the
    frame. Uses multiple decode passes for reliability: plain grayscale,
    OpenCV grayscale, and adaptive threshold.
    """
    if not _load_libs():
        raise AppError(
            "Aadhaar QR decoding is unavailable on this server "
            "(missing system 'zbar' library). Please install it and restart.",
            503,
        )
    raw = image_bytes
    passes = []

    # 1. PIL grayscale
    try:
        from PIL import Image

        img = Image.open(io.BytesIO(raw)).convert("L")
        passes.append(("pil", img))
    except Exception as e:
        raise AppError(f"Could not read image: {e}", 400)

    # 2. OpenCV grayscale + threshold (better for full-card photos)
    try:
        import cv2
        import numpy as np

        nparr = np.frombuffer(raw, np.uint8)
        bgr = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        if bgr is not None:
            gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
            passes.append(("cv-gray", gray))
            _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            passes.append(("cv-thresh", thresh))
    except Exception:
        pass

    seen = set()
    codes = []

    def _collect(results):
        for r in results:
            try:
                val = r.data.decode("utf-8")
            except Exception:
                continue
            if val not in seen:
                seen.add(val)
                codes.append(val)

    for _, frame in passes:
        try:
            _collect(_pyzbar.decode(frame))
        except Exception:
            continue

    # If nothing found yet, the QR may be small within a large card photo.
    # Use OpenCV's QRCodeDetector (finds QR regions) and a tiled/upscaled
    # pyzbar scan to locate QR codes that full-frame decoding misses.
    try:
        import cv2
        import numpy as np

        nparr = np.frombuffer(raw, np.uint8)
        bgr = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        if bgr is not None:
            # 3. OpenCV QRCodeDetector — robust to small QRs in big frames.
            if not codes:
                try:
                    qd = cv2.QRCodeDetector()
                    ret, info, _pts, _ = qd.detectAndDecodeMulti(bgr)
                    if ret and isinstance(info, (list, tuple)):
                        for item in info:
                            if item and str(item).strip() and str(item).strip() not in seen:
                                seen.add(str(item).strip())
                                codes.append(str(item).strip())
                except Exception:
                    pass

            # 4. Tiled + upscaled pyzbar scan for small / low-res QRs.
            if not codes:
                gray2 = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
                hgt, wdt = gray2.shape
                for tilesize in (250, 300, 400):
                    step = max(80, tilesize // 2)
                    for top in range(0, max(1, hgt - tilesize + 1), step):
                        for left in range(0, max(1, wdt - tilesize + 1), step):
                            tile = gray2[top : top + tilesize, left : left + tilesize]
                            for fac in (2, 3):
                                t = cv2.resize(
                                    tile, None, fx=fac, fy=fac, interpolation=cv2.INTER_CUBIC
                                )
                                try:
                                    _collect(_pyzbar.decode(t))
                                except Exception:
                                    continue
                            if codes:
                                break
                        if codes:
                            break
                    if codes:
                        break
    except Exception:
        pass

    return codes


def _ensure_pil_grayscale(img):
    # pyzbar expects a PIL image; grayscale works reliably
    return img


def verify_qr_payload(raw: str) -> dict:
    """
    Verify the raw QR string of an Aadhaar card.

    Returns dict with verified fields or raises AppError.
    """
    if not raw or not raw.strip():
        raise AppError("Empty QR payload", 400)

    # 1. Try the modern pyaadhaar "secure QR" path first.
    try:
        if _load_libs() and _pyaadhaar["isSecureQr"](raw):
            secure = _pyaadhaar["AadhaarSecureQr"](int(raw))
            decoded = secure.decodeddata() or {}
            photo = None
            try:
                image = secure.image()
                if image is not None:
                    buf = io.BytesIO()
                    image.convert("RGB").save(buf, format="JPEG", quality=85)
                    photo = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()
            except Exception:
                photo = None
            if photo is None:
                photo = _photo_from_dict(decoded)
            return _extract_verified(decoded, raw, photo)
    except Exception:
        # Fall through to our own offline XML verify below.
        pass

    # 2. Fallback: our own offline Aadhaar XML/QR decoder + signature verification.
    return _verify_offline(raw)


def _photo_from_dict(decoded: dict):
    for key in ("photo", "image", "_photo", "Photo", "imageBytes"):
        v = decoded.get(key)
        if not v:
            continue
        if isinstance(v, bytes):
            return "data:image/jpeg;base64," + base64.b64encode(v).decode()
        s = str(v)
        if s.startswith("data:image"):
            return s
        return "data:image/jpeg;base64," + s
    return None


def _verify_offline(raw: str) -> dict:
    try:
        xml = aadhaar.decode_qr(raw)
        data = aadhaar.verify_signed_xml(xml)
    except aadhaar.AadhaarVerificationError as e:
        raise AppError(f"Aadhaar verification failed: {e}", 400)
    if not data.get("verified", True):
        raise AppError("Aadhaar QR could not be verified (unsecure/old format)", 400)
    photo = data.get("photo")
    if photo and not str(photo).startswith("data:image"):
        photo = "data:image/jpeg;base64," + str(photo)
    return {
        "verified": True,
        "name": data.get("name"),
        "dob": data.get("dob"),
        "gender": data.get("gender"),
        "yob": data.get("yob"),
        "address": data.get("address"),
        "uid": data.get("uid") or data.get("aadhaarNumber"),
        "photo": photo,
    }


def _mask_uid(uid):
    if not uid:
        return None
    s = str(uid).replace("-", "").replace("*", "").strip()
    if len(s) >= 4:
        return "XXXX XXXX " + s[-4:]
    return uid


def _extract_verified(decoded: dict, raw: str, photo=None) -> dict:
    # pyaadhaar secure QR decoded data key names vary; normalise them.
    def g(*keys):
        for k in keys:
            v = decoded.get(k)
            if v:
                return v
        return None

    name = g("full_name", "name", "Name")
    dob = g("date_of_birth", "dob", "DOB", "DateOfBirth")
    gender = g("gender", "Gender")
    address = g("address", "Address")
    yob = g("year_of_birth", "yob", "YearOfBirth")
    careof = g("care_of", "careof", "CareOf")
    uid = _mask_uid(g("aadhaar_number", "aadhaarNumber", "uid", "pruid"))

    if not name:
        raise AppError("Aadhaar QR decoded but no valid identity fields found", 400)
    return {
        "verified": True,
        "name": name,
        "dob": dob,
        "gender": gender,
        "yob": yob,
        "address": address,
        "careof": careof,
        "uid": uid,
        "photo": photo,
    }


def verify_aadhaar_qr(image_bytes: bytes) -> dict:
    """Decode + verify an Aadhaar card from an uploaded image and return fields."""
    codes = decode_qr_from_image(image_bytes)
    if not codes:
        raise AppError("No Aadhaar QR code detected in the image", 400)
    if len(codes) > 1:
        raise AppError("Multiple QR codes detected; please provide a single Aadhaar card", 400)
    return verify_qr_payload(codes[0])


def scan_aadhaar(image_bytes: bytes) -> dict:
    """Alias used by the upload router (multipart image)."""
    return verify_aadhaar_qr(image_bytes)
